Honour the config directory set by configure
Ensure that ipset_remove_all_tmp_sets() is defined before it can
be called in firehol_exit().

diff --git a/sbin/firehol.in b/sbin/firehol.in
--- a/sbin/firehol.in
+++ b/sbin/firehol.in
@@ -276,6 +276,9 @@ if [ "@AUTOCONF_RUN@" = "Y" ]
 then
 	FIREHOL_AUTOSAVE="@FIREHOL_AUTOSAVE@"
 	FIREHOL_AUTOSAVE6="@FIREHOL_AUTOSAVE6@"
+	FIREHOL_CONFIG_DIR="@FIREHOL_CONFIG_DIR@"
+else
+	FIREHOL_CONFIG_DIR="/etc/firehol"
 fi
 
 # --- BEGIN OF FIREHOL DEFAULTS ---
@@ -288,8 +291,8 @@ fi
 
 # FireHOL config directory.
 # EVEN IF YOU CHANGE THIS, THE firehol-defaults.conf FILE
-# SHOULD STILL EXIST IN /etc/firehol
-FIREHOL_CONFIG_DIR="/etc/firehol"
+# SHOULD STILL EXIST IN THE ORIGINAL $FIREHOL_CONFIG_DIR
+FIREHOL_CONFIG_DIR="$FIREHOL_CONFIG_DIR"
 
 # FireHOL services directory.
 # FireHOL will look into this directory for service
@@ -1290,6 +1293,26 @@ failure() {
 	FIREHOL_PROGRESS_MESSAGES=("${FIREHOL_PROGRESS_MESSAGES[@]}")
 }
 
+FIREHOL_IPSET_TMP_COUNTER=0
+declare -A FIREHOL_IPSET_TMP_SETS=()
+
+ipset_done_all_tmp_sets() {
+	# empty temp variables to prevent cleanup from running at exit
+	FIREHOL_IPSET_TMP_SETS=()
+}
+
+ipset_remove_all_tmp_sets() {
+	if [ ${ENABLE_IPSET} -eq 1 ]
+	then
+		local x=
+		for x in ${!FIREHOL_IPSET_TMP_SETS[@]}
+		do
+			${IPSET_CMD} ${IPSET_DESTROY_OPTION} "${x}" >/dev/null 2>&1
+		done
+		ipset_done_all_tmp_sets
+	fi
+}
+
 firehol_exit() {
 	local restored="NO"
 	if [ $RUNNING_ON_TERMINAL -eq 1 ]
@@ -1597,8 +1620,9 @@ fi
 # Generate firehol-defaults.conf file
 if [ ! -f "${FIREHOL_CONFIG_DIR}/firehol-defaults.conf" ]
 then
-	${EGREP_CMD} "^# --- BEGIN OF FIREHOL DEFAULTS ---" -A 1000 "${PROGRAM_FILE}" |\
-		${EGREP_CMD} "^# --- END OF FIREHOL DEFAULTS ---" -B 1000 >"${FIREHOL_CONFIG_DIR}/firehol-defaults.conf" || exit 1
+	$SED_CMD -n -e "s:\$FIREHOL_CONFIG_DIR:$FIREHOL_CONFIG_DIR:" \
+		-e '/^# --- BEGIN OF FIREHOL DEFAULTS ---/,/^# --- END OF FIREHOL DEFAULTS ---/p' \
+		"${PROGRAM_FILE}" > "${FIREHOL_CONFIG_DIR}/firehol-defaults.conf" || exit 1
 	${CHOWN_CMD} root:root "${FIREHOL_CONFIG_DIR}/firehol-defaults.conf"	|| exit 1
 	${CHMOD_CMD} 600 "${FIREHOL_CONFIG_DIR}/firehol-defaults.conf"	|| exit 1
 fi
@@ -3617,8 +3641,6 @@ ipset() {
 	esac
 }
 
-FIREHOL_IPSET_TMP_COUNTER=0
-declare -A FIREHOL_IPSET_TMP_SETS=()
 ipset_apply() {
 	local name="${1}" file="${2}" swap="${3}" entries=0 opts= hash= tmpname=
 
@@ -3687,23 +3709,6 @@ ipset_apply() {
 	if [ ! "${file}" -ef "${FIREHOL_SPOOL_DIR}/ipset.${name}.rules" ]
 		then
 		$CP_CMD "${file}" "${FIREHOL_SPOOL_DIR}/ipset.${name}.rules"
-	fi
-}
-
-ipset_done_all_tmp_sets() {
-	# empty temp variables to prevent cleanup from running at exit
-	FIREHOL_IPSET_TMP_SETS=()
-}
-
-ipset_remove_all_tmp_sets() {
-	if [ ${ENABLE_IPSET} -eq 1 ]
-	then
-		local x=
-		for x in ${!FIREHOL_IPSET_TMP_SETS[@]}
-		do
-			${IPSET_CMD} ${IPSET_DESTROY_OPTION} "${x}" >/dev/null 2>&1
-		done
-		ipset_done_all_tmp_sets
 	fi
 }
 
