tproxy support. beta. may not work. fixed issue #25

diff --git a/sbin/firehol.in b/sbin/firehol.in
--- a/sbin/firehol.in
+++ b/sbin/firehol.in
@@ -2928,6 +2928,83 @@ transparent_squid() {
 	transparent_proxy 80 "$@"
 }
 
+FIREHOL_TPROXY_MARK="0xffff"
+FIREHOL_TPROXY_IP_ROUTE_TABLE="999"
+FIREHOL_TPROXY_ROUTE_DEVICE="lo"
+
+tproxy_setup_ip_route() {
+	local x=
+	for x in inet inet6
+	do
+		# remove the existing ip rules for this mark
+		ip -f $x rule del from all fwmark $FIREHOL_TPROXY_MARK >/dev/null 2>&1
+
+		# remove the existing rules from the ip route table
+		ip -f $x route flush table $FIREHOL_TPROXY_IP_ROUTE_TABLE >/dev/null 2>&1
+
+		# add the ip rule to match the mask and forward it to the proper ip route table for tproxy
+		ip -f $x rule add from all fwmark $FIREHOL_TPROXY_MARK lookup $FIREHOL_TPROXY_IP_ROUTE_TABLE || return 1
+
+		# add the route to forward all traffic to lo, on the ip route table for tproxy
+		ip -f $x route add local default dev $FIREHOL_TPROXY_ROUTE_DEVICE table $FIREHOL_TPROXY_IP_ROUTE_TABLE || return 1
+	done
+
+	# disable the reverse path discovery for lo
+	echo 0 > /proc/sys/net/ipv4/conf/default/rp_filter
+	echo 0 > /proc/sys/net/ipv4/conf/all/rp_filter
+	echo 0 > /proc/sys/net/ipv4/conf/$FIREHOL_TPROXY_ROUTE_DEVICE/rp_filter
+}
+
+tproxy_count=0
+tproxy() {
+	work_realcmd_helper $FUNCNAME "$@"
+	
+	set_work_function -ne "Initializing $FUNCNAME"
+	
+	require_work clear || ( error "$FUNCNAME cannot be used in '${work_cmd}'. Put it before any '${work_cmd}' definition."; return 1 )
+	
+	local ports="${1}"; shift
+	local tproxy_type="${1}"; shift
+	local redirect="${1}"; shift
+	
+	test -z "${redirect}" && error "Proxy listening port is empty" && return 1
+	case "${tproxy_type}" in
+		port)
+			local tproxy_action_options="tproxy-mark $FIREHOL_TPROXY_MARK on-port ${redirect}"
+			;;
+		ip)
+			local tproxy_action_options="tproxy-mark $FIREHOL_TPROXY_MARK on-ip ${redirect}"
+			;;
+		*)
+			error "Invalid tproxy type '$tproxy_type'. It can either be 'port' or 'ip'."
+			return 1
+			;;
+	esac
+	
+	tproxy_count=$[tproxy_count + 1]
+	
+	set_work_function "Setting up rules for catching routed tcp/${ports} traffic"
+	
+	create_chain mangle "in_tproxy.${tproxy_count}" PREROUTING "$@" outface any proto tcp dport "${ports}" || return 1
+
+	create_chain mangle "in_tproxy.${tproxy_count}.divert" "in_tproxy.${tproxy_count}" custom '-m socket' || return 1
+	rule table mangle chain "in_tproxy.${tproxy_count}.divert" action MARK to $FIREHOL_TPROXY_MARK
+	rule table mangle chain "in_tproxy.${tproxy_count}.divert" action ACCEPT
+
+	rule table mangle chain "in_tproxy.${tproxy_count}" proto tcp action TPROXY ${tproxy_action_options} || return 1
+	
+	FIREHOL_NAT=1
+	FIREHOL_ROUTING=1
+	
+	if [ $tproxy_count -eq 1 ]
+	then
+		postprocess tproxy_setup_ip_route
+	fi
+
+	return 0
+}
+
+
 nat_count=0
 nat_helper() {
 #	work_realcmd_helper $FUNCNAME "$@"
@@ -5371,7 +5448,7 @@ rule() {
 						
 					redirect|REDIRECT)
 						action="REDIRECT"
-						if [ "${1}" = "to-port" -o "${1}" = "to" ]
+						if [ "${1}" = "on-port" -o "${1}" = "to-port" -o "${1}" = "to" ]
 						then
 							local -a action_param=("--to-ports" "${2}")
 							shift 2
@@ -5382,6 +5459,35 @@ rule() {
 						if [ ! "A${table}" = "A-t nat" ]
 						then
 							error "${action} must on a the 'nat' table."
+							return 1
+						fi
+						;;
+						
+					tproxy|TPROXY)
+						action="TPROXY"
+						local -a action_param=()
+						if [ "${1}" = "mark" -o "${1}" = "tproxy-mark" ]
+						then
+							action_param=("--tproxy-mark" "${2}")
+							shift 2
+						fi
+
+						if [ "${1}" = "on-port" -o "${1}" = "to-port" -o "${1}" = "to" ]
+						then
+							action_param=(${action_param[@]} "--on-port" "${2}")
+							shift 2
+						elif [ "${1}" = "on-ip" -o "${1}" = "to-ip" ]
+						then
+							action_param=(${action_param[@]} "--on-ip" "${2}")
+							shift 2
+						else
+							error "${action} requires a 'on-port' or 'on-ip' argument."
+							return 1
+						fi
+
+						if [ ! "A${table}" = "A-t mangle" ]
+						then
+							error "${action} cannot be on '$table', only on a the 'mangle' table."
 							return 1
 						fi
 						;;
