Fixup commands not using _CMD variables
Also fix remaining problems around autodetection
Both were exposed by the new unittest strategy

diff --git a/sbin/firehol.in b/sbin/firehol.in
--- a/sbin/firehol.in
+++ b/sbin/firehol.in
@@ -95,40 +95,6 @@ FIREHOL_DEFAULT_WORKING_DIRECTORY="${PWD}"
 # Make sure we don't get localized results
 export LC_ALL=C
 
-RUNNING_ON_TERMINAL=0
-if [ "z$1" = "z-nc" ]
-then
-	shift
-else
-	test -t 2 && RUNNING_ON_TERMINAL=1
-	if [ -t 2 -a $[$(tput colors 2>/dev/null)] -ge 8 ]
-	then
-		# Enable colors
-		COLOR_RESET="\e[0m"
-		COLOR_BLACK="\e[30m"
-		COLOR_RED="\e[31m"
-		COLOR_GREEN="\e[32m"
-		COLOR_YELLOW="\e[33m"
-		COLOR_BLUE="\e[34m"
-		COLOR_PURPLE="\e[35m"
-		COLOR_CYAN="\e[36m"
-		COLOR_WHITE="\e[37m"
-		COLOR_BGBLACK="\e[40m"
-		COLOR_BGRED="\e[41m"
-		COLOR_BGGREEN="\e[42m"
-		COLOR_BGYELLOW="\e[43m"
-		COLOR_BGBLUE="\e[44m"
-		COLOR_BGPURPLE="\e[45m"
-		COLOR_BGCYAN="\e[46m"
-		COLOR_BGWHITE="\e[47m"
-		COLOR_BOLD="\e[1m"
-		COLOR_DIM="\e[2m"
-		COLOR_UNDERLINED="\e[4m"
-		COLOR_BLINK="\e[5m"
-		COLOR_INVERTED="\e[7m"
-	fi
-fi
-
 # ------------------------------------------------------------------------------
 # XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 # ------------------------------------------------------------------------------
@@ -838,9 +804,6 @@ MULTICAST_IPV6="FF00::/16"
 
 # --- END OF FIREHOL DEFAULTS ---
 
-# disable the spinner when we don't run on a terminal
-test ${RUNNING_ON_TERMINAL} -eq 0 && FIREHOL_ENABLE_SPINNER=0
-
 # load the defaults if they exist
 if [ -f "${FIREHOL_CONFIG_DIR}/firehol-defaults.conf" ]
 then
@@ -904,7 +867,12 @@ which_cmd() {
 	fi
 	shift
 
-	eval $name="'${cmd}' ${@}"
+	if [ $# -eq 0 ]
+	then
+		eval $name="'${cmd}'"
+	else
+		eval $name="'${cmd} ${@}'"
+	fi
 	return 0
 }
 
@@ -941,7 +909,11 @@ require_cmd() {
 		return 0
 	elif [ $block -eq 0 ]
 	then
-		eval "NEED_${var}"="'$@'"
+		eval set -- "$@"
+		for cmd in "$@"
+		do
+			eval "NEED_${var}"="\$NEED_${var}' ${cmd/ */}'"
+		done
 		return 0
 	fi
 
@@ -951,7 +923,7 @@ require_cmd() {
 	fi
 
 	echo >&2
-	echo >&2 "ERROR:	FIREHOL REQUIRES THESE COMMANDS:"
+	echo >&2 "ERROR:	FIREHOL REQUIRES ONE OF THESE COMMANDS:"
 	echo >&2
 	echo >&2 "	${@}"
 	echo >&2
@@ -1028,6 +1000,7 @@ Y|FOLD_CMD|@FOLD@|fold
 Y|GREP_CMD|@GREP@|grep
 Y|HEAD_CMD|@HEAD@|head
 Y|TAIL_CMD|@TAIL@|tail
+Y|LS_CMD|@LS@|ls
 Y|LSMOD_CMD|@LSMOD@|lsmod
 Y|MKDIR_CMD|@MKDIR@|mkdir
 Y|MKTEMP_CMD|@MKTEMP@|mktemp
@@ -1055,12 +1028,50 @@ Y|PAGER_CMD|@PAGER@|less more pager cat
 Y|RENICE_CMD|@RENICE@|renice :
 Y|STTY_CMD|@STTY@|stty :
 N|ZCAT_CMD|@ZCAT@|zcat gzcat "gzip -dc"
-N|MODPROBE_CMD|@INSMOD@|modprobe insmod
+N|MODPROBE_CMD|@INSMOD@|'modprobe -q' insmod
 N|IP_CMD|@IP@|ip
 N|SS_CMD|@SS@|ss
 N|DATE_CMD|@DATE@|date
-N|HOSTNAME_CMD|@HOSTNAME_CMD@|hostname
+N|HOSTNAME_CMD|@HOSTNAME@|hostname
+N|TPUT_CMD|@TPUT@|tput
 !
+
+RUNNING_ON_TERMINAL=0
+if [ "z$1" = "z-nc" ]
+then
+	shift
+else
+	test -t 2 && RUNNING_ON_TERMINAL=1
+	if [ -t 2 -a $[$(tput colors 2>/dev/null)] -ge 8 ]
+	then
+		# Enable colors
+		COLOR_RESET="\e[0m"
+		COLOR_BLACK="\e[30m"
+		COLOR_RED="\e[31m"
+		COLOR_GREEN="\e[32m"
+		COLOR_YELLOW="\e[33m"
+		COLOR_BLUE="\e[34m"
+		COLOR_PURPLE="\e[35m"
+		COLOR_CYAN="\e[36m"
+		COLOR_WHITE="\e[37m"
+		COLOR_BGBLACK="\e[40m"
+		COLOR_BGRED="\e[41m"
+		COLOR_BGGREEN="\e[42m"
+		COLOR_BGYELLOW="\e[43m"
+		COLOR_BGBLUE="\e[44m"
+		COLOR_BGPURPLE="\e[45m"
+		COLOR_BGCYAN="\e[46m"
+		COLOR_BGWHITE="\e[47m"
+		COLOR_BOLD="\e[1m"
+		COLOR_DIM="\e[2m"
+		COLOR_UNDERLINED="\e[4m"
+		COLOR_BLINK="\e[5m"
+		COLOR_INVERTED="\e[7m"
+	fi
+fi
+
+# disable the spinner when we don't run on a terminal
+test ${RUNNING_ON_TERMINAL} -eq 0 && FIREHOL_ENABLE_SPINNER=0
 
 FIREHOL_HAVE_IPRANGE=1
 IPRANGE_WARNING=0
@@ -1274,7 +1285,10 @@ failure() {
 
 firehol_exit() {
 	local restored="NO"
-	$STTY_CMD sane
+	if [ $RUNNING_ON_TERMINAL -eq 1 ]
+	then
+		$STTY_CMD sane
+	fi
 	if [ \( -f "${FIREHOL_SAVED}" -o -f "${FIREHOL_SAVED6}" \) -a "${FIREHOL_MODE}" = "START" ]
 	then
 		echo >&2
@@ -1547,7 +1561,7 @@ ${MKDIR_CMD} "${FIREHOL_DIR}/fast/table6s" || exit 1
 # this is needed only when we are going to save the firewall
 # with iptables-save.
 file open 20 "${FIREHOL_DIR}/firewall_restore_commands.sh" w || exit 1
-cat >&20 <<'EOFMTL'
+$CAT_CMD >&20 <<'EOFMTL'
 #!/bin/sh
 # Generated by FireHOL to execute additional actions
 # to restore the generated firewall.
@@ -3278,7 +3292,7 @@ rules_custom() {
 # Load all the services.
 # All these files should start with: #FHVER: 1
 cd "${FIREHOL_SERVICES_DIR}" || exit 1
-for f in `ls *.conf 2>/dev/null`
+for f in `$LS_CMD *.conf 2>/dev/null`
 do
 	cd "${FIREHOL_SERVICES_DIR}" || exit 1
 	
@@ -5392,7 +5406,7 @@ ipset_apply() {
 	if [ "${hash}" = "iphash" -o "${hash}" = "hash:ip" -o "${hash}" = "nethash" -o "${hash}" = "hash:net" ]
 	then
 		# count the entries in the file
-		entries=$(wc -l <"${file}")
+		entries=$($WC_CMD -l <"${file}")
 
 		# if the user gave maxelem, keep the max
 		if [ ${entries} -lt ${FIREHOL_IPSETS_MAXELEM[$name]} ]
@@ -6256,10 +6270,10 @@ load_kernel_module() {
 		LOADED_KERNEL_MODULES="${LOADED_KERNEL_MODULES} ${mod}"
 
 		require_cmd MODPROBE_CMD
-		${MODPROBE_CMD} ${mod} -q
+		${MODPROBE_CMD} ${mod}
 		if [ $? -gt 0 -a $? -ne 17 ] # 17: insmod, already loaded
 		then
-			check_kernel_module ${mod} || runtime_error warn 1 "$(config_line)" ${MODPROBE_CMD} ${mod} -q
+			check_kernel_module ${mod} || runtime_error warn 1 "$(config_line)" ${MODPROBE_CMD} ${mod}
 		fi
 	fi
 	return 0
@@ -6853,14 +6867,14 @@ rule_action_param() {
 							overflow="REJECT"
 						
 						# if we have a custom overflow action, parse it.
-						test "${action_param[3]}" = "overflow" && overflow="`echo "${action_param[4]}" | tr "a-z" "A-Z"`"
+						test "${action_param[3]}" = "overflow" && overflow="`echo "${action_param[4]}" | $TR_CMD "a-z" "A-Z"`"
 						
 						# unset the action_param, so that if this rule does not include NEW connections,
 						# we will not append anything to the generated iptables statements.
 						action_param=()
 						
 						# find is this rule matches NEW connections
-						local has_new=`echo "${state}" | grep -i NEW`
+						local has_new=`echo "${state}" | $GREP_CMD -i NEW`
 						local do_accept_limit=0
 						if [ -z "${statenot}" ]
 						then
@@ -6875,7 +6889,7 @@ rule_action_param() {
 						# to pass.
 						if [ "${do_accept_limit}" = "1" ]
 						then
-							local accept_limit_chain="`echo "ACC LIM ${freq} ${burst} ${overflow}" | tr " /." "___"`"
+							local accept_limit_chain="`echo "ACC LIM ${freq} ${burst} ${overflow}" | $TR_CMD " /." "___"`"
 							
 							# does the chain we need already exist?
 							#if [ ! -f "${FIREHOL_CHAINS_DIR}/${accept_limit_chain}.${iptables_cmd}" ]
@@ -6884,7 +6898,7 @@ rule_action_param() {
 								# the chain does not exist. create it.
 								$iptables_cmd -t ${table} -N "${accept_limit_chain}"
 								FIREHOL_CHAINS[${accept_limit_chain}.${iptables_cmd}]="1"
-								#touch "${FIREHOL_CHAINS_DIR}/${accept_limit_chain}.${iptables_cmd}"
+								#$TOUCH_CMD "${FIREHOL_CHAINS_DIR}/${accept_limit_chain}.${iptables_cmd}"
 								
 								# first, if the traffic is not a NEW connection, allow it.
 								# doing this first will speed up normal traffic.
@@ -6923,7 +6937,7 @@ rule_action_param() {
 						action_param=()
 						
 						# find is this rule matches NEW connections
-						local has_new=`echo "${state}" | grep -i NEW`
+						local has_new=`echo "${state}" | $GREP_CMD -i NEW`
 						local do_accept_recent=0
 						if [ -z "${statenot}" ]
 						then
@@ -6938,7 +6952,7 @@ rule_action_param() {
 						# to pass.
 						if [ "${do_accept_recent}" = "1" ]
 						then
-							local accept_recent_chain="`echo "ACC REC $name $seconds $hits" | tr " /." "___"`"
+							local accept_recent_chain="`echo "ACC REC $name $seconds $hits" | $TR_CMD " /." "___"`"
 							
 							# does the chain we need already exist?
 							#if [ ! -f "${FIREHOL_CHAINS_DIR}/${accept_recent_chain}.${iptables_cmd}" ]
@@ -6947,7 +6961,7 @@ rule_action_param() {
 								# the chain does not exist. create it.
 								$iptables_cmd -t ${table} -N "${accept_recent_chain}"
 								FIREHOL_CHAINS[${accept_recent_chain}.${iptables_cmd}]="1"
-								#touch "${FIREHOL_CHAINS_DIR}/${accept_recent_chain}.${iptables_cmd}"
+								#$TOUCH_CMD "${FIREHOL_CHAINS_DIR}/${accept_recent_chain}.${iptables_cmd}"
 								
 								# first, if the traffic is not a NEW connection, allow it.
 								# doing this first will speed up normal traffic.
@@ -6984,7 +6998,7 @@ rule_action_param() {
 							# the chain does not exist. create it.
 							$iptables_cmd -t ${table} -N "${name}"
 							FIREHOL_CHAINS[${name}.${iptables_cmd}]="1"
-							#touch "${FIREHOL_CHAINS_DIR}/${name}.${iptables_cmd}"
+							#$TOUCH_CMD "${FIREHOL_CHAINS_DIR}/${name}.${iptables_cmd}"
 							
 							$iptables_cmd -A "${name}" -m conntrack --ctstate ESTABLISHED -j ACCEPT
 							
@@ -9862,14 +9876,14 @@ work_realcmd_helper() {
 }
 
 wait_for_interface() {
-	local iface="${1}" timeout=60 found=0 start=`date +%s` addr=
+	local iface="${1}" timeout=60 found=0 start=`$DATE_CMD +%s` addr=
 	shift
 
 	[ -n "$1" ] && timeout="${1}"
 
-	while [ "`date +%s`" -lt $(($start+$timeout)) -a $found -eq 0 ]
+	while [ "`$DATE_CMD +%s`" -lt $(($start+$timeout)) -a $found -eq 0 ]
 	do
-		addr=`ip addr show $iface 2> /dev/null | ${SED_CMD} -n 's/^ *inet \([^ ]*\).*/\1/p'`
+		addr=`$IP_CMD addr show $iface 2> /dev/null | ${SED_CMD} -n 's/^ *inet \([^ ]*\).*/\1/p'`
 		[ -n "$addr" ] && found=1
 		[ $found -eq 0 ] && sleep 0.5
 	done
@@ -9922,7 +9936,7 @@ firehol_save_activated_firewall() {
 		${CHOWN_CMD} root:root "${FIREHOL_SPOOL_DIR}/ipv4.rules"
 		${CHMOD_CMD} 600 "${FIREHOL_SPOOL_DIR}/ipv4.rules"
 	else
-		test -f "${FIREHOL_SPOOL_DIR}/ipv4.rules" && rm "${FIREHOL_SPOOL_DIR}/ipv4.rules"
+		test -f "${FIREHOL_SPOOL_DIR}/ipv4.rules" && $RM_CMD "${FIREHOL_SPOOL_DIR}/ipv4.rules"
 	fi
 	
 	if [ -f "${FIREHOL_SPOOL_DIR}/ipv6.enable" ]
@@ -9937,7 +9951,7 @@ firehol_save_activated_firewall() {
 		${CHOWN_CMD} root:root "${FIREHOL_SPOOL_DIR}/ipv6.rules"
 		${CHMOD_CMD} 600 "${FIREHOL_SPOOL_DIR}/ipv6.rules"
 	else
-		test -f "${FIREHOL_SPOOL_DIR}/ipv6.rules" && rm "${FIREHOL_SPOOL_DIR}/ipv6.rules"
+		test -f "${FIREHOL_SPOOL_DIR}/ipv6.rules" && $RM_CMD "${FIREHOL_SPOOL_DIR}/ipv6.rules"
 	fi
 
 	printf "%q " "${FIREHOL_ARGS[@]}" >"${FIREHOL_LAST_SUCCESSFUL_COMMAND}"
@@ -9954,7 +9968,7 @@ firehol_can_restore_saved_firewall() {
 		&& return 1
 
 	local args="`printf "%q " "${FIREHOL_ARGS[@]}"`"
-	local old_args="`cat "${FIREHOL_LAST_SUCCESSFUL_COMMAND}"`"
+	local old_args="`$CAT_CMD "${FIREHOL_LAST_SUCCESSFUL_COMMAND}"`"
 	test ! "${args}" = "${old_args}" \
 		&& warning "Saved firewall cannot be restored because it was run with different parameters." \
 		&& return 2
@@ -10244,7 +10258,7 @@ case "${arg}" in
 			echo
 			echo "--- NAT IPv6 -------------------------------------------------------------------"
 			echo
-			if grep -q '^nat$' /proc/net/ip6_tables_names
+			if $GREP_CMD -q '^nat$' /proc/net/ip6_tables_names
 			then
 				${IP6TABLES_CMD} -t nat -nxvL
 			else
@@ -10425,7 +10439,7 @@ case "${arg}" in
 		ipset_done_all_tmp_sets
 
 		# let the user know
-		success "$(( $(wc -l <"${tmp}"))) entries" # "Updating ipset '${name}' with options: ${*}"
+		success "$(( $($WC_CMD -l <"${tmp}"))) entries" # "Updating ipset '${name}' with options: ${*}"
 
 		# keep it for restoration
 		if [ -f "${FIREHOL_SPOOL_DIR}/ipset.${name}.rules" ]
@@ -10712,7 +10726,7 @@ Special interactive commands: help, show, quit
 
 EOF
 	HISTFILE="${HOME}/.firehol_history"
-	test ! -f ${HISTFILE} && touch ${HISTFILE}
+	test ! -f ${HISTFILE} && $TOUCH_CMD ${HISTFILE}
 	history -r
 
 	while [ 1 = 1 ]
@@ -11505,8 +11519,8 @@ fi
 
 if [ $status4 -eq 0 -a $status6 -eq 0 ]
 then
-	test -f ${FIREHOL_SAVED}.new && mv ${FIREHOL_SAVED}.new ${FIREHOL_SAVED}
-	test -f ${FIREHOL_SAVED6}.new && mv ${FIREHOL_SAVED6}.new ${FIREHOL_SAVED6}
+	test -f ${FIREHOL_SAVED}.new && $MV_CMD ${FIREHOL_SAVED}.new ${FIREHOL_SAVED}
+	test -f ${FIREHOL_SAVED6}.new && $MV_CMD ${FIREHOL_SAVED6}.new ${FIREHOL_SAVED6}
 
 	success # "Saving active firewall to a temporary file"
 else
@@ -11816,6 +11830,8 @@ fi
 
 if [ -n "$WAIT_FOR_IFACE" ]
 then
+	require_cmd DATE_CMD
+	require_cmd IP_CMD
 	for i in "$WAIT_FOR_IFACE"
 	do
 		wait_for_interface $i
@@ -11874,7 +11890,7 @@ then
 		esac
 
 		cd $FIREHOL_DIR/fast/${n}s || exit 1
-		for firehol_table in `ls`
+		for firehol_table in `$LS_CMD`
 		do
 			case "${firehol_table}" in
 				raw)		chains="PREROUTING OUTPUT" ;;
@@ -11970,8 +11986,8 @@ then
 			
 			# find the line
 			echo >&2 "Offending line:"
-			line=`cat "${FIREHOL_OUTPUT}.log" | grep "Error occurred at line: " | cut -d ':' -f 2`
-			test -z "$line" && line=`cat "${FIREHOL_OUTPUT}.log" | grep "iptables-restore: line " | grep failed | cut -d ' ' -f 3`
+			line=`$CAT_CMD "${FIREHOL_OUTPUT}.log" | $GREP_CMD "Error occurred at line: " | $CUT_CMD -d ':' -f 2`
+			test -z "$line" && line=`$CAT_CMD "${FIREHOL_OUTPUT}.log" | $GREP_CMD "iptables-restore: line " | $GREP_CMD failed | $CUT_CMD -d ' ' -f 3`
 			${CAT_CMD} "${FIREHOL_OUTPUT}.fast" | ${HEAD_CMD} -n $line | ${TAIL_CMD} -n 1 >&2
 			echo >&2
 
@@ -11993,8 +12009,8 @@ then
 
 				# find the line
 				echo >&2 "Offending line:"
-				line=`cat "${FIREHOL_OUTPUT}.log" | grep "Error occurred at line: " | cut -d ':' -f 2`
-				test -z "$line" && line=`cat "${FIREHOL_OUTPUT}.log" | grep "ip6tables-restore: line " | grep failed | cut -d ' ' -f 3`
+				line=`$CAT_CMD "${FIREHOL_OUTPUT}.log" | $GREP_CMD "Error occurred at line: " | $CUT_CMD -d ':' -f 2`
+				test -z "$line" && line=`$CAT_CMD "${FIREHOL_OUTPUT}.log" | $GREP_CMD "ip6tables-restore: line " | $GREP_CMD failed | $CUT_CMD -d ' ' -f 3`
 				${CAT_CMD} "${FIREHOL_OUTPUT}.fast6" | ${HEAD_CMD} -n $line | ${TAIL_CMD} -n 1 >&2
 				echo >&2
 
@@ -12084,28 +12100,28 @@ FIREHOL_ACTIVATED_SUCCESSFULLY=1
 # last, keep a copy of the firewall we activated, on disk
 
 file close 20
-mv "${FIREHOL_DIR}/firewall_restore_commands.sh" "${FIREHOL_SPOOL_DIR}/firewall_restore_commands.sh"
-chown root:root "${FIREHOL_SPOOL_DIR}/firewall_restore_commands.sh"
-chmod 700 "${FIREHOL_SPOOL_DIR}/firewall_restore_commands.sh"
+$MV_CMD "${FIREHOL_DIR}/firewall_restore_commands.sh" "${FIREHOL_SPOOL_DIR}/firewall_restore_commands.sh"
+$CHOWN_CMD root:root "${FIREHOL_SPOOL_DIR}/firewall_restore_commands.sh"
+$CHMOD_CMD 700 "${FIREHOL_SPOOL_DIR}/firewall_restore_commands.sh"
 
 # keep track if we do ipv4
 if [ $ENABLE_IPV4 -eq 1 ]
 then
-	touch "${FIREHOL_SPOOL_DIR}/ipv4.enable"
-	chown root:root "${FIREHOL_SPOOL_DIR}/ipv4.enable"
-	chmod 600 "${FIREHOL_SPOOL_DIR}/ipv4.enable"
+	$TOUCH_CMD "${FIREHOL_SPOOL_DIR}/ipv4.enable"
+	$CHOWN_CMD root:root "${FIREHOL_SPOOL_DIR}/ipv4.enable"
+	$CHMOD_CMD 600 "${FIREHOL_SPOOL_DIR}/ipv4.enable"
 else
-	test -f "${FIREHOL_SPOOL_DIR}/ipv4.enable" && rm "${FIREHOL_SPOOL_DIR}/ipv4.enable"
+	test -f "${FIREHOL_SPOOL_DIR}/ipv4.enable" && $RM_CMD "${FIREHOL_SPOOL_DIR}/ipv4.enable"
 fi
 
 # keep track if we do ipv6
 if [ $ENABLE_IPV6 -eq 1 ]
 then
-	touch "${FIREHOL_SPOOL_DIR}/ipv6.enable"
-	chown root:root "${FIREHOL_SPOOL_DIR}/ipv6.enable"
-	chmod 600 "${FIREHOL_SPOOL_DIR}/ipv6.enable"
+	$TOUCH_CMD "${FIREHOL_SPOOL_DIR}/ipv6.enable"
+	$CHOWN_CMD root:root "${FIREHOL_SPOOL_DIR}/ipv6.enable"
+	$CHMOD_CMD 600 "${FIREHOL_SPOOL_DIR}/ipv6.enable"
 else
-	test -f "${FIREHOL_SPOOL_DIR}/ipv6.enable" && rm "${FIREHOL_SPOOL_DIR}/ipv6.enable"
+	test -f "${FIREHOL_SPOOL_DIR}/ipv6.enable" && $RM_CMD "${FIREHOL_SPOOL_DIR}/ipv6.enable"
 fi
 
 # save the rules to ${FIREHOL_SPOOL_DIR}
@@ -12155,7 +12171,7 @@ then
 	then
 		progress "Saving firewall to '${FIREHOL_AUTOSAVE}'"
 	
-		cat "${FIREHOL_SPOOL_DIR}/ipv4.rules" >${FIREHOL_AUTOSAVE}
+		$CAT_CMD "${FIREHOL_SPOOL_DIR}/ipv4.rules" >${FIREHOL_AUTOSAVE}
 		if [ ! $? -eq 0 ]
 		then
 			syslog err "Failed to save new firewall to '${FIREHOL_AUTOSAVE}'."
@@ -12171,7 +12187,7 @@ then
 	then
 		progress "Saving IPv6 firewall to '${FIREHOL_AUTOSAVE6}'"
 	
-		cat "${FIREHOL_SPOOL_DIR}/ipv6.rules" >${FIREHOL_AUTOSAVE6}
+		$CAT_CMD "${FIREHOL_SPOOL_DIR}/ipv6.rules" >${FIREHOL_AUTOSAVE6}
 		if [ ! $? -eq 0 ]
 		then
 			syslog err "Failed to save new IPv6 firewall to '${FIREHOL_AUTOSAVE6}'."
