committed rate is required for group classes; overcommitting is now checked for group classes too

diff --git a/sbin/fireqos.in b/sbin/fireqos.in
--- a/sbin/fireqos.in
+++ b/sbin/fireqos.in
@@ -406,14 +406,18 @@ syslog() {
 }
 
 error() {
+	echo >&2 -e "$COLOR_RED$COLOR_BOLD"
 	echo >&2
 	echo >&2
-	echo >&2 "FAILED: $@"
+	echo >&2 "ERROR:"
+	echo -e >&2 "$@"
+	echo >&2
+	echo >&2 -e "$COLOR_RESET"
 	exit 1
 }
 
 warning() {
-	echo >&2 -e ":	\e[1;31mWARNING! $* \e[0m"
+	echo >&2 -e ":	${COLOR_YELLOW}${COLOR_BOLD}WARNING! $* ${COLOR_RESET}"
 }
 
 runcmd() {
@@ -1016,7 +1020,7 @@ check_constrains() {
 	then
 		if [ $ceil -gt $parent_ceil ]
 		then
-			warning "ceil ($((ceil * 8 / 1000))kbit) is more than its parent's ceil ($((parent_ceil * 8 / 1000))kbit). Fixed it by settting ceil to parent's ceil."
+			warning "ceil ($((ceil * 8 / 1000))kbit) is higher than its parent's ceil ($((parent_ceil * 8 / 1000))kbit). Fixed it by settting ceil to parent's ceil."
 			eval "${prefix}_ceil=$parent_ceil"
 		fi
 	fi
@@ -1025,7 +1029,7 @@ check_constrains() {
 	then
 		if [ $burst -gt $parent_burst ]
 		then
-			warning "burst ($burst bytes) is less than its parent's burst ($parent_burst bytes). Fixed it by setting burst to parent's burst."
+			warning "burst ($burst bytes) is higher than its parent's burst ($parent_burst bytes). Fixed it by setting burst to parent's burst."
 			eval "${prefix}_burst=$parent_burst"
 		fi
 	fi
@@ -1034,12 +1038,21 @@ check_constrains() {
 	then
 		if [ $cburst -gt $parent_cburst ]
 		then
-			warning "cburst ($cburst bytes) is less than its parent's cburst ($parent_cburst bytes). Fixed it by setting cburst to parent's cburst."
+			warning "cburst ($cburst bytes) is higher than its parent's cburst ($parent_cburst bytes). Fixed it by setting cburst to parent's cburst."
 			eval "${prefix}_cburst=$parent_cburst"
 		fi
 	fi
 	
 	return 0
+}
+
+check_committed_rate() {
+	if [ $parent_rate -ge $parent_sumrate ]
+	then
+		echo -e ": $class_tabs${COLOR_BLUE}${COLOR_BOLD}committed rate $((parent_sumrate * 8 / 1000))kbit ($((parent_sumrate * 100 / parent_rate))%), the remaining $(((parent_rate - parent_sumrate)*8/1000))kbit will be spare bandwidth.${COLOR_RESET}"
+	else
+		echo -e ": $class_tabs${COLOR_RED}${COLOR_BOLD}committed rate $((parent_sumrate * 8 / 1000))kbit, ($((parent_sumrate * 100 / parent_rate))%), overbooked by $((-(parent_rate - parent_sumrate)*8/1000))kbit. PLEASE FIX.${COLOR_RESET}"
+	fi
 }
 
 interface_major=
@@ -1082,13 +1095,7 @@ interface_close() {
 			parent_default_added=1
 		fi
 		
-		echo -n ":	interface committed rate $((parent_sumrate * 8 / 1000))kbit, $((parent_sumrate * 100 / parent_rate))%, "
-		if [ $parent_rate -ge $parent_sumrate ]
-		then
-			echo "the remaining $(((parent_rate - parent_sumrate)*8/1000))kbit will be spare bandwidth."
-		else
-			echo "overbooked by $(((parent_rate - parent_sumrate)*8/1000))kbit. PLEASE FIX."
-		fi
+		check_committed_rate
 
 		# NOT NEEDED - the default for interfaces works via kernel.
 		# match all class default flowid $interface_major:$parent_default_class prio 0xffff
@@ -1206,6 +1213,8 @@ interface() {
 	
 	[ -z "$interface_priority_mode" ] && interface_priority_mode="priority"
 	
+	# IPv, this is only used by matches
+	# here we just give the defaults for inheritance to work
 	if [ -z "$interface_ipv4" -a -z "$interface_ipv6" ]
 	then
 		interface_ipv4=1
@@ -1316,6 +1325,7 @@ interface() {
 	
 	parent_push interface
 	
+	# default IPv for the classes
 	class_ipv4=$interface_ipv4
 	class_ipv6=$interface_ipv6
 	class_name=root
@@ -1419,6 +1429,8 @@ class() {
 			# by the kernel. This rule, sends all remaining traffic to the inner default.
 			match all class default flowid $parent_major:$parent_default_class prio 0xffff
 			
+			check_committed_rate
+
 			if [ $parent_stab -eq 1 ]
 			then
 				parent_pull
@@ -1441,15 +1453,15 @@ class() {
 	
 	class_name="$1"; shift
 	
-	# increase the global class counter
+	# increase the interface global class counter
 	interface_global_class_counter=$((interface_global_class_counter + 1))
 	
 	# increase the parent's class counter
 	# this is used for determining the minor of the class
 	parent_class_counter=$((parent_class_counter + 1))
 	
-	# if this is the default class, use the pre-defined
-	# id, otherwise use the classid we just increased
+	# if this is the default class, use the pre-defined id,
+	# otherwise use the classid we just increased
 	if [ "$class_name" = "default" ]
 	then
 		local id=$parent_default_class
@@ -1506,8 +1518,12 @@ class() {
 	[ $class_prio -gt 7 ] && class_prio=7
 	
 	# if not specified, set the minimum rate
-	[ -z "$class_rate" ] && class_rate=$interface_minrate
-	
+	if [ -z "$class_rate" ]
+	then
+		[ $class_group -eq 1 ] && error "Class group '$class_name' does not specify a committed rate.\nClass groups should have a committed rate."
+		class_rate=$interface_minrate
+	fi
+
 	# class rate cannot go bellow 1/100 of the interface rate
 	[ $class_rate -lt $interface_minrate ] && class_rate=$interface_minrate
 	
@@ -1534,23 +1550,21 @@ class() {
 		test ! -z "$class_mpu"		&& local stab="$stab mpu $class_mpu"
 	fi
 	
+	# check it the user overbooked the parent
+	parent_sumrate=$((parent_sumrate + $class_rate))
+	local info_color="$COLOR_BLUE"
+	[ $parent_sumrate -gt $parent_rate ] && local info_color="$COLOR_RED"
+	
 	if [ $class_group -eq 1 -a ! -z "$stab" ]
 	then
-		echo -e " $COLOR_BOLD$COLOR_BLUE($class_classid, $((class_rate*8/1000))kbit, prio $class_prio, MTU $class_mtu, quantum $class_quantum)$COLOR_RESET"
+		echo -e " $info_color$COLOR_BOLD($class_classid, $((class_rate*8/1000))kbit, prio $class_prio, MTU $class_mtu, quantum $class_quantum)$COLOR_RESET"
 	else
-		echo -e " $COLOR_BOLD$COLOR_BLUE($class_classid, $((class_rate*8/1000))kbit, prio $class_prio)$COLOR_RESET"
+		echo -e " $info_color$COLOR_BOLD($class_classid, $((class_rate*8/1000))kbit, prio $class_prio)$COLOR_RESET"
 	fi
 	
 	# keep track of all classes in the interface, so that the matches can name them to get their flowid
 	interface_classes="$interface_classes $class_name|$class_filters_flowid"
 	interface_classes_ids="$interface_classes_ids $ncid"
-	
-	# check it the user overbooked the parent
-	parent_sumrate=$((parent_sumrate + $class_rate))
-	if [ $parent_sumrate -gt $parent_rate ]
-	then
-		warning "The classes under $parent_name commit more bandwidth (+$(( (parent_sumrate - parent_rate) * 8 / 1000 ))kbit) than the available rate."
-	fi
 	
 	class_default_class=
 	if [ $class_group -eq 1 ]
