first attempt to make synproxy work with dynamic IP; added options FIREHOL_SYNPROXY_EXCLUDE_OWNER which once set to 1 will enable matching synproxy packets with owner - it will require "src not" though; made it drop invalid TCP ACK packets from server to client; made synproxy marking a little bit strictier by matching SYN packet

diff --git a/sbin/firehol.in b/sbin/firehol.in
--- a/sbin/firehol.in
+++ b/sbin/firehol.in
@@ -545,6 +545,13 @@ FIREHOL_SYNPROXY_OPTIONS="--sack-perm --timestamp --wscale 7 --mss 1460"
 # Default: 0
 FIREHOL_SYNPROXY_LOG=0
 
+# When enabled, synproxy will exclude for the SYNPROXY->SERVER match
+# all the packets that have an UID or a GID (ownmer matches).
+# When enabled, dst is not required for synproxy and synproxy can
+# be used on dynamic IPs (it requires an 'src not; though).
+# Default: 0
+FIREHOL_SYNPROXY_EXCLUDE_OWNER=0
+
 # Trust loopback?
 # loose     = Trust device lo unconditionally
 # strict    = Trust only IPs 127.0.0.0/8 and ::1 on device lo
@@ -3519,8 +3526,8 @@ synproxy() {
 	work_realcmd_helper ${FUNCNAME} "${@}"
 
 	local	where="${1}" chain= match=() action= action_args=() log=() \
-		inface=() dst=() overwrite_in=() overwrite_out=() \
-		x= dohooks=0
+		inface=() dst=() src=() overwrite_in=() overwrite_out=() \
+		x= dohooks=0 owner=()
 	shift
 
 	set_work_function -ne "Initializing ${FUNCNAME}"
@@ -3548,6 +3555,7 @@ synproxy() {
 				case "${1,,}" in
 					inface)		inface=("${inface[@]}" ${2//,/ }) ;;
 					dst|dst4|dst6)	dst=("${dst[@]}" ${2//,/ }) ;;
+					src|src4|src6)	src=("${src[@]}" ${2//,/ }) ;;
 				esac
 				;;
 		esac
@@ -3567,10 +3575,21 @@ synproxy() {
 	fi
 
 	# make sure we have a dst/dst4/dst6
-	if [ -z "${dst[*]}" ]
+	if [ ${FIREHOL_SYNPROXY_EXCLUDE_OWNER} -eq 0 -a \( -z "${dst[*]}" -o "${dst[*]}" = "not" \) ]
 	then
 		error "You should set 'dst' IPs for SYNPROXY."
 		return 1
+	fi
+
+	if [ ${FIREHOL_SYNPROXY_EXCLUDE_OWNER} -eq 1 ]
+	then
+		owner=(user not 0-65535 group not 0-65535)
+
+		if [ \( -z "${dst[*]}" -o "${dst[*]}" = "not" \) -a ! "${src[*]}" = "not" ]
+		then
+			error "You have to set a 'dst' or a 'src not' with SYNPROXY."
+			return 1
+		fi
 	fi
 
 	if running_both
@@ -3675,9 +3694,9 @@ synproxy() {
 		test ${FIREHOL_SYNPROXY_LOG} -eq 1 && log=(loglimit "CLIENT->SYNPROXY SYN or ACK")
 		rule table filter chain ${chain} "${match[@]}" ${overwrite_in[@]} proto tcp state INVALID,UNTRACKED "${log[@]}" action SYNPROXY ${FIREHOL_SYNPROXY_OPTIONS} || return 1
 
-		set_work_function "SYNPROXY->CLIENT ACK packet at filter.OUTPUT"
-		test ${FIREHOL_SYNPROXY_LOG} -eq 1 && log=(loglimit "SYNPROXY->CLIENT ACK")
-		rule table filter chain OUTPUT reverse "${match[@]}" ${overwrite_in[@]} proto tcp state INVALID,UNTRACKED "${log[@]}" action ACCEPT nosoftwarnings outface any physout any || return 1
+		set_work_function "SYNPROXY->CLIENT SYN+ACK packet at filter.OUTPUT"
+		test ${FIREHOL_SYNPROXY_LOG} -eq 1 && log=(loglimit "SYNPROXY->CLIENT SYN,ACK")
+		rule table filter chain OUTPUT reverse custom '-m tcp --tcp-flags SYN,RST,ACK SYN,ACK' "${match[@]}" ${overwrite_in[@]} proto tcp state INVALID,UNTRACKED "${log[@]}" action ACCEPT nosoftwarnings outface any physout any "${owner[@]}" || return 1
 		
 		# Once the client receives the ACK from SYNPROXY, it will send an ACK back.
 		# This ACK will be routed again to SYNPROXY (it will be UNTRACKED too).
@@ -3686,7 +3705,7 @@ synproxy() {
 
 		set_work_function "SYNPROXY->SERVER marking SYN packet at mangle.OUTPUT"
 		test ${FIREHOL_SYNPROXY_LOG} -eq 1 && log=(loglimit "SYNPROXY->SERVER SYN MARK")
-		rule table mangle chain OUTPUT "${match[@]}" proto tcp state NEW "${log[@]}" action MARK to ${synproxy_mark} nosoftwarnings inface any physin any ${overwrite_out[@]} || return 1
+		rule table mangle chain OUTPUT "${match[@]}" proto tcp custom '-m tcp --syn' state NEW "${log[@]}" action MARK to ${synproxy_mark} nosoftwarnings inface any physin any ${overwrite_out[@]} "${owner[@]}" || return 1
 
 		case "${action}" in
 			DNAT)
@@ -3713,6 +3732,10 @@ synproxy() {
 				set_work_function "SYNPROXY->SERVER accepting DNAT'd SYN packet at filter.OUTPUT"
 				test ${FIREHOL_SYNPROXY_LOG} -eq 1 && log=(loglimit "SYNPROXY->SERVER DNAT'd OUT")
 				rule table filter chain SYNPROXY2SERVER_OUT "${match[@]}" proto tcp "${log[@]}" action ACCEPT nosoftwarnings inface any physin any ${ip} ${port} || return 1
+
+				set_work_function "SERVER->CLIENT droping INVALID ACK"
+				test ${FIREHOL_SYNPROXY_LOG} -eq 1 && log=(loglimit "SERVER->CLIENT INVALID ACK")
+				rule table filter chain FORWARD reverse "${match[@]}" custom '-m tcp --tcp-flags RST,ACK ACK' proto tcp state INVALID "${log[@]}" nosoftwarnings ${ip} ${port} action DROP || return 1
 				;;
 
 			REDIRECT)
@@ -3733,6 +3756,10 @@ synproxy() {
 				set_work_function "SYNPROXY->SERVER accepting re-routed packet at device lo at filter.INPUT"
 				test ${FIREHOL_SYNPROXY_LOG} -eq 1 && log=(loglimit "SYNPROXY->SERVER lo IN")
 				rule table filter chain SYNPROXY2SERVER_IN "${match[@]}" proto tcp "${log[@]}" action ACCEPT nosoftwarnings inface lo physin any outface any physout any dst "${localhost}"  dport ${action_args[1]} || return 1
+
+				set_work_function "SERVER->CLIENT droping INVALID ACK"
+				test ${FIREHOL_SYNPROXY_LOG} -eq 1 && log=(loglimit "SERVER->CLIENT INVALID ACK")
+				rule table filter chain OUTPUT reverse "${match[@]}" custom '-m tcp --tcp-flags RST,ACK ACK' proto tcp state INVALID "${log[@]}" nosoftwarnings action DROP outface any physout any dport ${action_args[1]} || return 1
 
 				# this requires routing device lo
 				set_work_function "SYNPROXY->SERVER enabling routing ${inface[@]} <-> lo"
@@ -3757,6 +3784,10 @@ synproxy() {
 					test ${FIREHOL_SYNPROXY_LOG} -eq 1 && log=(loglimit "SYNPROXY->SERVER ACTION ${action^^} IN")
 					rule table filter chain SYNPROXY2SERVER_IN "${match[@]}" proto tcp "${log[@]}" nosoftwarnings action "${action}" "${action_args[@]}" inface lo physin any outface any physout any || return 1
 
+					set_work_function "SERVER->CLIENT droping INVALID ACK"
+					test ${FIREHOL_SYNPROXY_LOG} -eq 1 && log=(loglimit "SERVER->CLIENT INVALID ACK")
+					rule table filter chain OUTPUT reverse "${match[@]}" custom '-m tcp --tcp-flags RST,ACK ACK' proto tcp state INVALID "${log[@]}" nosoftwarnings action DROP outface any physout any || return 1
+
 					# this requires routing device lo
 					set_work_function "SYNPROXY->SERVER enabling routing ${inface[@]} <-> lo"
 					setup_lo_for_synproxy "${inface[@]}" || return 1
@@ -3764,6 +3795,11 @@ synproxy() {
 					set_work_function "SYNPROXY->SERVER executing action ${action} at filter.OUTPUT (the packet should leave the machine)"
 					test ${FIREHOL_SYNPROXY_LOG} -eq 1 && log=(loglimit "SYNPROXY->SERVER ACTION ${action^^} OUT")
 					rule table filter chain SYNPROXY2SERVER_OUT "${match[@]}" proto tcp "${log[@]}" nosoftwarnings action "${action}" "${action_args[@]}" inface any physin any || return 1
+
+					set_work_function "SERVER->CLIENT droping INVALID ACK"
+					test ${FIREHOL_SYNPROXY_LOG} -eq 1 && log=(loglimit "SERVER->CLIENT INVALID ACK")
+					rule table filter chain FORWARD reverse "${match[@]}" custom '-m tcp --tcp-flags RST,ACK ACK' proto tcp state INVALID "${log[@]}" nosoftwarnings action DROP || return 1
+
 				fi
 				;;
 		esac
@@ -8914,7 +8950,7 @@ rule() {
 			
 			*)
 				owner_arg=("-m" "owner")
-				uid_arg=(${ownernot} "--uid-owner" "${tuid}")
+				uid_arg=(${uidnot} "--uid-owner" "${tuid}")
 				;;
 		esac
 	
@@ -8929,7 +8965,7 @@ rule() {
 			
 			*)
 				owner_arg=("-m" "owner")
-				gid_arg=(${ownernot} "--gid-owner" "${tgid}")
+				gid_arg=(${gidnot} "--gid-owner" "${tgid}")
 				;;
 		esac
 	
