added manual page for cthelper; added connlimit to blacklist and iptrap; added stateful option to blacklist; FIREHOL_DROP_ORPHAN_TCP_ACK_FIN fixed to match only ACK+FIN ignoring all other flags; similarly added FIREHOL_DROP_ORPHAN_TCP_ACK_RST, FIREHOL_DROP_ORPHAN_TCP_ACK, FIREHOL_DROP_ORPHAN_TCP_RST, FIREHOL_DROP_ORPHAN_IPV4_ICMP_TYPE3 (to drop orphan destination unreachable packets); added the word BLOCKED to the log messages of INVALID packets dropped; updated the man pages

diff --git a/sbin/firehol.in b/sbin/firehol.in
--- a/sbin/firehol.in
+++ b/sbin/firehol.in
@@ -427,6 +427,39 @@ FIREHOL_LOG_DROP_INVALID=1
 # Default: 1
 FIREHOL_DROP_ORPHAN_TCP_ACK_FIN=1
 
+# If set to 1, FireHOL will silently drop orphan TCP packets with ACK,RST set.
+# In modern kernels, the connection tracker detects closed sockets
+# and removes them from memory before receiving the ACK,RST from the remote
+# party. This makes FireHOL log these packets when they will be received.
+# To silently drop these packets, enable this option.
+# Default: 1
+FIREHOL_DROP_ORPHAN_TCP_ACK_RST=1
+
+# If set to 1, FireHOL will silently drop orphan TCP packets with ACK set.
+# In modern kernels, the connection tracker detects closed sockets
+# and removes them from memory before receiving the ACK from the remote
+# party. This makes FireHOL log these packets when they will be received.
+# To silently drop these packets, enable this option.
+# Default: 1
+FIREHOL_DROP_ORPHAN_TCP_ACK=1
+
+# If set to 1, FireHOL will silently drop orphan TCP packets with RST set.
+# In modern kernels, the connection tracker detects closed sockets
+# and removes them from memory before receiving the RST from the remote
+# party. This makes FireHOL log these packets when they will be received.
+# To silently drop these packets, enable this option.
+# Default: 1
+FIREHOL_DROP_ORPHAN_TCP_RST=1
+
+# If set to 1, FireHOL will silently drop orphan ICMP destination unreachable
+# packets. In modern kernels, the connection tracker detects closed sockets
+# and removes them from memory before receiving the ICMP destination
+# unreachable from the remote party. This makes FireHOL log these packets when
+# they will be received.
+# To silently drop these packets, enable this option.
+# Default: 1
+FIREHOL_DROP_ORPHAN_IPV4_ICMP_TYPE3=1
+
 # If enabled FireHOL will create a chain per server/client statement and jump
 # to it from the main flow. Normaly this jump is only required for clarity.
 # So it is advised to leave this setting to 0, for a more efficient firewall.
@@ -4825,6 +4858,12 @@ blacklist() {
 			shift
 			;;
 
+		statefull)
+			mode=2
+			name="bs"
+			shift
+			;;
+
 		*)	;;
 	esac
 	
@@ -4843,6 +4882,12 @@ blacklist() {
 			log)
 				logopts_in_arg=(log "${2}-IN")
 				logopts_out_arg=(log "${2}-OUT")
+				shift 2
+				;;
+
+			connlog)
+				logopts_in_arg=(connlog "${2}-IN")
+				logopts_out_arg=(connlog "${2}-OUT")
 				shift 2
 				;;
 
@@ -4903,6 +4948,10 @@ blacklist() {
 		done
 
 	else
+		local state=
+
+		[ ${mode} -eq 2 ] && state="state NEW"
+
 		# bi-directional stateless
 		# no traffic from/to them
 
@@ -4910,7 +4959,7 @@ blacklist() {
 
 		for x in INPUT FORWARD
 		do
-			rule table filter chain ${x}  in "${inface[@]}" src "${src[*]}" action "${chain}.in" || return 1
+			rule table filter chain ${x}  in "${inface[@]}" src "${src[*]}" ${state} action "${chain}.in" || return 1
 		done
 
 		set_work_function "Blacklist output chain"
@@ -4946,7 +4995,7 @@ blacklist() {
 		# iptables does not accept REJECT on mangle - we are forced to use filter for this
 		for x in FORWARD OUTPUT
 		do
-			rule table filter chain ${x} out reverse "${inface[@]}" src "${src[*]}" action "${chain}.out" || return 1
+			rule table filter chain ${x} out reverse "${inface[@]}" src "${src[*]}" ${state} action "${chain}.out" || return 1
 		done
 	fi
 
@@ -5055,7 +5104,7 @@ iptrap() {
 				break
 				;;
 
-			log|loglimit)
+			log|loglimit|connlog)
 				logopts_arg=("${1}" "${2}")
 				shift
 				;;
@@ -11980,9 +12029,53 @@ firewall_filtering_policy_common() {
 
 		# Silently drop orphan TCP/ACK FIN packets
 		# before droping INVALID below, otherwise these will be logged as INVALID too
-		${iptables_cmd} -t filter -A INPUT -p tcp --tcp-flags ALL ACK,FIN -m conntrack --ctstate NEW,INVALID -j DROP
-		${iptables_cmd} -t filter -A OUTPUT -p tcp --tcp-flags ALL ACK,FIN -m conntrack --ctstate NEW,INVALID -j DROP
-		${iptables_cmd} -t filter -A FORWARD -p tcp --tcp-flags ALL ACK,FIN -m conntrack --ctstate NEW,INVALID -j DROP
+		${iptables_cmd} -t filter -A INPUT -p tcp --tcp-flags ACK,FIN ACK,FIN -m conntrack --ctstate NEW,INVALID -j DROP
+		${iptables_cmd} -t filter -A OUTPUT -p tcp --tcp-flags ACK,FIN ACK,FIN -m conntrack --ctstate NEW,INVALID -j DROP
+		${iptables_cmd} -t filter -A FORWARD -p tcp --tcp-flags ACK,FIN ACK,FIN -m conntrack --ctstate NEW,INVALID -j DROP
+	fi
+
+	if [ "${FIREHOL_DROP_ORPHAN_TCP_ACK_RST}" = "1" ]
+	then
+		set_work_function "Silently droping TCP ACK+RST packets (option: FIREHOL_DROP_ORPHAN_TCP_ACK_RST)"
+
+		# Silently drop orphan TCP/ACK RST packets
+		# before droping INVALID below, otherwise these will be logged as INVALID too
+		${iptables_cmd} -t filter -A INPUT -p tcp --tcp-flags ACK,RST ACK,RST -m conntrack --ctstate NEW,INVALID -j DROP
+		${iptables_cmd} -t filter -A OUTPUT -p tcp --tcp-flags ACK,RST ACK,RST -m conntrack --ctstate NEW,INVALID -j DROP
+		${iptables_cmd} -t filter -A FORWARD -p tcp --tcp-flags ACK,RST ACK,RST -m conntrack --ctstate NEW,INVALID -j DROP
+	fi
+
+	if [ "${FIREHOL_DROP_ORPHAN_TCP_ACK}" = "1" ]
+	then
+		set_work_function "Silently droping TCP ACK packets (option: FIREHOL_DROP_ORPHAN_TCP_ACK)"
+
+		# Silently drop orphan TCP/ACK packets
+		# before droping INVALID below, otherwise these will be logged as INVALID too
+		${iptables_cmd} -t filter -A INPUT -p tcp --tcp-flags ACK ACK -m conntrack --ctstate NEW,INVALID -j DROP
+		${iptables_cmd} -t filter -A OUTPUT -p tcp --tcp-flags ACK ACK -m conntrack --ctstate NEW,INVALID -j DROP
+		${iptables_cmd} -t filter -A FORWARD -p tcp --tcp-flags ACK ACK -m conntrack --ctstate NEW,INVALID -j DROP
+	fi
+
+	if [ "${FIREHOL_DROP_ORPHAN_TCP_RST}" = "1" ]
+	then
+		set_work_function "Silently droping TCP ACK packets (option: FIREHOL_DROP_ORPHAN_TCP_RST)"
+
+		# Silently drop orphan TCP/RST packets
+		# before droping INVALID below, otherwise these will be logged as INVALID too
+		${iptables_cmd} -t filter -A INPUT -p tcp --tcp-flags RST RST -m conntrack --ctstate NEW,INVALID -j DROP
+		${iptables_cmd} -t filter -A OUTPUT -p tcp --tcp-flags RST RST -m conntrack --ctstate NEW,INVALID -j DROP
+		${iptables_cmd} -t filter -A FORWARD -p tcp --tcp-flags RST RST -m conntrack --ctstate NEW,INVALID -j DROP
+	fi
+
+	if [ "${iptables_cmd}" = "iptables" -a "${FIREHOL_DROP_ORPHAN_IPV4_ICMP_TYPE3}" = "1" ]
+	then
+		set_work_function "Silently droping ICMP destination-unreachable packets (option: FIREHOL_DROP_ORPHAN_IPV4_ICMP_TYPE3)"
+
+		# Silently drop orphan ICMP/TYPE3 packets
+		# before droping INVALID below, otherwise these will be logged as INVALID too
+		${iptables_cmd} -t filter -A INPUT -p icmp --icmp-type destination-unreachable -m conntrack --ctstate NEW,INVALID -j DROP
+		${iptables_cmd} -t filter -A OUTPUT -p icmp --icmp-type destination-unreachable -m conntrack --ctstate NEW,INVALID -j DROP
+		${iptables_cmd} -t filter -A FORWARD -p icmp --icmp-type destination-unreachable -m conntrack --ctstate NEW,INVALID -j DROP
 	fi
 
 	# Drop all invalid packets.
@@ -11993,9 +12086,9 @@ firewall_filtering_policy_common() {
 
 		if [ ${FIREHOL_LOG_DROP_INVALID} -eq 1 ]
 		then
-			rule table filter chain INPUT state INVALID action DROP loglimit "INVALID IN"
-			rule table filter chain OUTPUT state INVALID action DROP loglimit "INVALID OUT"
-			rule table filter chain FORWARD state INVALID action DROP loglimit "INVALID PASS"
+			rule table filter chain INPUT state INVALID action DROP loglimit "BLOCKED INVALID IN"
+			rule table filter chain OUTPUT state INVALID action DROP loglimit "BLOCKED INVALID OUT"
+			rule table filter chain FORWARD state INVALID action DROP loglimit "BLOCKED INVALID PASS"
 		else
 			${iptables_cmd} -t filter -A INPUT -m conntrack --ctstate INVALID -j DROP
 			${iptables_cmd} -t filter -A OUTPUT -m conntrack --ctstate INVALID -j DROP
