moved RUN_DIR to /tmp because certain distros have very small /var/run tmpfs - /tmp is the proper place for temporary files

diff --git a/sbin/update-ipsets.in b/sbin/update-ipsets.in
--- a/sbin/update-ipsets.in
+++ b/sbin/update-ipsets.in
@@ -504,8 +504,12 @@ fi
 BASE_DIR="/etc/firehol/ipsets"
 
 # where to keep the run files
-# a subdirectory will be created as RUN_DIR
+# this is used for the lock file
 RUN_PARENT_DIR="/var/run"
+
+# where to keep the tmp files
+# a subdirectory will be created as RUN_DIR
+TMP_DIR="/tmp"
 
 # where to keep the history files
 HISTORY_DIR="${BASE_DIR}/history"
@@ -739,23 +743,41 @@ exlcusive_lock
 
 if [ -z "${BASE_DIR}" ]
 	then
-	error "BASE_DIR cannot be empty."
+	error "BASE_DIR is unset. Set it in '${CONFIG_FILE}'."
 	exit 1
 fi
 
 if [ -z "${RUN_PARENT_DIR}" ]
 	then
-	error "RUN_PARENT_DIR cannot be empty."
+	error "RUN_PARENT_DIR is unset. Set it in '${CONFIG_FILE}'."
+	exit 1
+fi
+
+if [ ! -d "${RUN_PARENT_DIR}" ]
+	then
+	error "RUN_PARENT_DIR='${RUN_PARENT_DIR}' does not exist. Set it in '${CONFIG_FILE}'."
+	exit 1
+fi
+
+if [ -z "${TMP_DIR}" ]
+	then
+	error "TMP_DIR is unset. Set it in '${CONFIG_FILE}'."
+	exit 1
+fi
+
+if [ ! -d "${TMP_DIR}" ]
+	then
+	error "TMP_DIR='${TMP_DIR}' does not exist. Set it in '${CONFIG_FILE}'."
 	exit 1
 fi
 
 if [ ! -z "${WEB_DIR}" -a ! -d "${WEB_DIR}" ]
 	then
-	warning "WEB_DIR is invalid. Disabling it."
+	warning "WEB_DIR='${WEB_DIR}' is invalid. Disabling web site updates. Set WEB_DIR in '${CONFIG_FILE}' to enable it."
 	WEB_DIR=
 fi
 
-for d in "${BASE_DIR}" "${RUN_PARENT_DIR}" "${HISTORY_DIR}" "${ERRORS_DIR}"
+for d in "${BASE_DIR}" "${HISTORY_DIR}" "${ERRORS_DIR}"
 do
 	[ -z "${d}" -o -d "${d}" ] && continue
 
@@ -767,10 +789,10 @@ cd "${BASE_DIR}" || exit 1
 # -----------------------------------------------------------------------------
 # CLEANUP
 
-RUN_DIR=$(${MKTEMP_CMD} -d "${RUN_PARENT_DIR}/update-ipsets-XXXXXXXXXX")
+RUN_DIR=$(${MKTEMP_CMD} -d "${TMP_DIR}/update-ipsets-XXXXXXXXXX")
 if [ $? -ne 0 ]
 	then
-	error "ERROR: Cannot create temporary directory in ${RUN_PARENT_DIR}."
+	error "ERROR: Cannot create temporary directory in ${TMP_DIR}."
 	exit 1
 fi
 
@@ -1785,13 +1807,24 @@ EOFSITEMAP1
 update_web() {
 	print_ipset_reset
 
-	local sitemap_date="$($DATE_CMD -I)"
+	if [ -z "${WEB_DIR}" -o ! -d "${WEB_DIR}" ]
+		then
+		echo >&2 "Web site update is disabled."
+		echo >&2 "To enable it set WEB_DIR in config file '${CONFIG_FILE}'."
+		return 1
+	fi
 
-	[ -z "${WEB_DIR}" -o ! -d "${WEB_DIR}" ] && return 1
-	[ "${#UPDATED_SETS[@]}" -eq 0 -a ! ${FORCE_WEB_REBUILD} -eq 1 ] && return 1
+	if [ "${#UPDATED_SETS[@]}" -eq 0 -a ! ${FORCE_WEB_REBUILD} -eq 1 ]
+		then
+		echo >&2 "Not updating web site - nothing updated in this run."
+		return 1
+	fi
 
-	local x= all=() updated=() geolite2_country=() ipdeny_country=() ip2location_country=() i= to_all= all_count=0
+	local all=() updated=() geolite2_country=() ipdeny_country=() ip2location_country=() \
+		x= i= to_all= all_count=0 \
+		sitemap_date="$($DATE_CMD -I)"
 
+	# the sitemap is re-generated on each run
 	sitemap_init "${sitemap_date}"
 
 	echo >&2 "-------------------------------------------------------------------------------"
