Clean up packaging
Use configure.ac to maintain version number
Remove redundant NEWS (ChangeLog) and AUTHORS (THANKS) files
Move hooks to their own directory
Rename README to README.md to format nicely on github
Generate README for tar by removing git specifics from README.md
Automate tagging when -rc or final version set in configure.ac
Improve pre-commit checking

diff --git a/packaging/git-build b/packaging/git-build
--- a/packaging/git-build
+++ b/packaging/git-build
@@ -1,32 +1,40 @@
 #!/bin/sh
 
+# When run from the top-level repository, performs a complete clean
+# and maintainer-mode rebuild of the FireHOL package.
+
 if [ ! -f .gitignore -o ! -f sbin/firehol.in ]
 then
-  echo "Run as ./packaging/dev-build from a firehol git repository"
+  echo "Run as ./packaging/git-build from a firehol git repository"
   exit 1
 fi
 
-clean=$(git status -s | grep "^?")
-
-if [ "$clean" ]
+# If we are genuinely in a git repo, try to clean it up, otherwise
+# just make the assumption
+if [ -d .git ]
 then
-  if [ "$1" != "-ok" ]
+  clean=$(git status -s | grep "^?")
+
+  if [ "$clean" ]
   then
-    echo "Warning: this script runs: git clean -d -f -x"
-    echo "         ensure all required ?? files are added, then re-run with '-ok'"
-    git status -s | grep '^?'
-    exit 1
+    if [ "$1" != "-ok" ]
+    then
+      echo "Warning: this script runs: git clean -d -f -x"
+      echo "         ensure all required ?? files are added, then re-run with '-ok'"
+      git status -s | grep '^?'
+      exit 1
+    fi
   fi
+
+  set -e
+  git clean -d -f -x
+  set +e
 fi
 
 set -e
-
-git clean -d -f -x
 ./autogen.sh
 ./configure --enable-maintainer-mode 
-sed -i -e '1idevelopment' NEWS
 set +e
 make dist
 status=$?
-sed -i -e '1d' NEWS
 exit $status
