fireqos now has same command detection as firehol
Update pre-commit script to detect entries missing from configure script
Update unittest to run fireqos without a PATH set
Update unittest with a view to running code coverage check

diff --git a/packaging/pre-commit b/packaging/pre-commit
--- a/packaging/pre-commit
+++ b/packaging/pre-commit
@@ -50,6 +50,8 @@ fi
 git show :ChangeLog > /tmp/staged-ChangeLog.$$
 git show :NEWS > /tmp/staged-NEWS.$$
 git show :sbin/firehol.in > /tmp/staged-sbin-firehol.in$$
+git show :sbin/fireqos.in > /tmp/staged-sbin-fireqos.in$$
+git show :configure.ac > /tmp/staged-configure.ac$$
 
 status=0
 
@@ -99,14 +101,53 @@ then
   cat /tmp/staged-sbin-firehol.problem-lines.$$
 fi
 
+sed -n -e 's/\("\$[^"}]*_CMD}\).*/\1/' \
+       -e T \
+       -e '/-z *"\$/b' \
+       -e '/\[ *"\$/b' \
+       -e '/= *"\$/b' \
+       -e '/eval *"\$/b' \
+       -e '{=}' \
+       /tmp/staged-sbin-fireqos.in$$ > /tmp/staged-sbin-fireqos.problem-lines.$$
+if [ -s /tmp/staged-sbin-fireqos.problem-lines.$$ ]
+then
+  status=1
+  echo 'Detected use(s) of "${SOMETHING_CMD}" in fireqos.in. Check lines:'
+  cat /tmp/staged-sbin-fireqos.problem-lines.$$
+fi
+
 grep "^[YN]|" /tmp/staged-sbin-firehol.in$$ > /tmp/staged-sbin-firehol.cmd$$
 for cmd in $(tr " " "\n" < /tmp/staged-sbin-firehol.in$$ |
-             sed -n -e 's/.*\(\<[A-Z_]*_CMD\).*/\1/p' | sort | uniq)
+             sed -n -e 's/.*\(\<[A-Z_]*\)_CMD.*/\1/p' | sort | uniq)
 do
-  if ! grep -q "^[YN]|$cmd|" /tmp/staged-sbin-firehol.cmd$$
+  if ! grep -q "^[YN]|${cmd}_CMD|" /tmp/staged-sbin-firehol.cmd$$
   then
     status=1
     echo "Missing definition of $cmd in firehol.in detection table."
+  fi
+  # Hostname is a special case - configure will expand it to running host,
+  # overwriting the value we wanted to use.
+  if [ "$cmd" = "HOSTNAME" ]; then cmd="HOSTNAMECMD"; fi
+  if ! grep -q "_${cmd}(\|\[$cmd\]" /tmp/staged-configure.ac$$
+  then
+    status=1
+    echo "Missing detection of $cmd for firehol.in in configure.ac"
+  fi
+done
+
+grep "^[YN]|" /tmp/staged-sbin-fireqos.in$$ > /tmp/staged-sbin-fireqos.cmd$$
+for cmd in $(tr " " "\n" < /tmp/staged-sbin-fireqos.in$$ |
+             sed -n -e 's/.*\(\<[A-Z_]*\)_CMD.*/\1/p' | sort | uniq)
+do
+  if ! grep -q "^[YN]|${cmd}_CMD|" /tmp/staged-sbin-fireqos.cmd$$
+  then
+    status=1
+    echo "Missing definition of $cmd in fireqos.in detection table."
+  fi
+  if ! grep -q "_${cmd}(\|\[$cmd\]" /tmp/staged-configure.ac$$
+  then
+    status=1
+    echo "Missing detection of $cmd for fireqos.in in configure.ac"
   fi
 done
 
