Implement version numbers
Using a combination of git attributes, ident and export-subst.
  - Scripts use Format: to emit tag or commit when exported
    or file Id if direct from git
  - configure script uses same mechanisms but cannot do a make dist
  - Brought bolierplate in line for both scripts

diff --git a/packaging/pre-commit b/packaging/pre-commit
--- a/packaging/pre-commit
+++ b/packaging/pre-commit
@@ -48,56 +48,57 @@ fi
 
 status=0
 git show :ChangeLog > /tmp/staged-ChangeLog.$$
-git show :configure.ac > /tmp/staged-config.$$
-git show :NEWS > /tmp/staged-NEWS.$$
-git show :sbin/firehol.in > /tmp/staged-firehol.$$
-
-configver=`sed -ne '/AC_INIT/s/.*,\[\(.*\)\],.*/\1/p' /tmp/staged-config.$$`
-innews=`head -n 10 /tmp/staged-NEWS.$$ | grep -F "$configver"`
-clogver=`sed -ne '1s/.*(\(.*\)).*/\1/p' /tmp/staged-ChangeLog.$$`
-fhver=`sed -ne '/FIREHOL_SCRIPT_VERSION/s/.*=\(.*\)/\1/p' /tmp/staged-firehol.$$`
-
-if [ ! "$configver" ]
-then
-  echo "Could not get version from configure.ac"
-  status=1
-fi
-
-if [ ! "$innews" ]
-then
-  echo "Version '$configver' from configure.ac not in NEWS"
-  status=1
-fi
-
-if [ ! "$fhver" ]
-then
-  echo "Could not get version from sbin/firehol.in"
-  status=1
-fi
-
-if [ ! "$clogver" ]
-then
-  echo "Could not get version from ChangeLog"
-  status=1
-fi
-
-if [ "$fhver" != "$configver" ]
-then
-  echo "Version '$configver' from configure.ac != '$fhver' from sbin/firehol.in"
-  status=1
-fi
-
-if [ "$clogver" != "$configver" ]
-then
-  echo "Version '$configver' from configure.ac != '$clogver' from ChangeLog"
-  status=1
-fi
-
+#git show :configure.ac > /tmp/staged-config.$$
+#git show :NEWS > /tmp/staged-NEWS.$$
+#git show :sbin/firehol.in > /tmp/staged-firehol.$$
+#
+#configver=`sed -ne '/AC_INIT/s/.*,\[\(.*\)\],.*/\1/p' /tmp/staged-config.$$`
+#innews=`head -n 10 /tmp/staged-NEWS.$$ | grep -F "$configver"`
+#clogver=`sed -ne '1s/.*(\(.*\)).*/\1/p' /tmp/staged-ChangeLog.$$`
+#fhver=`sed -ne '/FIREHOL_SCRIPT_VERSION/s/.*=\(.*\)/\1/p' /tmp/staged-firehol.$$`
+#
+#if [ ! "$configver" ]
+#then
+#  echo "Could not get version from configure.ac"
+#  status=1
+#fi
+#
+#if [ ! "$innews" ]
+#then
+#  echo "Version '$configver' from configure.ac not in NEWS"
+#  status=1
+#fi
+#
+#if [ ! "$fhver" ]
+#then
+#  echo "Could not get version from sbin/firehol.in"
+#  status=1
+#fi
+#
+#if [ ! "$clogver" ]
+#then
+#  echo "Could not get version from ChangeLog"
+#  status=1
+#fi
+#
+#if [ "$fhver" != "$configver" ]
+#then
+#  echo "Version '$configver' from configure.ac != '$fhver' from sbin/firehol.in"
+#  status=1
+#fi
+#
+#if [ "$clogver" != "$configver" ]
+#then
+#  echo "Version '$configver' from configure.ac != '$clogver' from ChangeLog"
+#  status=1
+#fi
+#
 ./packaging/check-log /tmp/staged-ChangeLog.$$
-
-rm -f /tmp/staged-ChangeLog.$$
-rm -f /tmp/staged-config.ac.$$
-rm -f /tmp/staged-NEWS.$$
+status=$?
+#
+#rm -f /tmp/staged-ChangeLog.$$
+#rm -f /tmp/staged-config.ac.$$
+#rm -f /tmp/staged-NEWS.$$
 
 if [ $status -ne 0 ]
 then
